### ISSUE TITLE
Does the order of elements in the JSON file matter?

### ISSUE THREAD

**Issue by jcoop1219** [jcoop1219/bme547tsh#2]
Does the order of keys/elements matter? Do they have to be listed in this order for each patient?
- First Name
- Last Name
- Age
- Gender
- Diagnosis
- TSH (containing a list of all of the test results)

Or can Diagnosis come after TSH?

**Comment by dward2** [comment]
No, the order is not important.  If you wrote code to read in the JSON file, it would put the information back in a dictionary.  The dictionary doesn't really have an order.  Each values would be matched with its key, and any "order" is really up to you when you go to output the results.  Make sense?

**Comment by jcoop1219** [comment]
Yup, makes sense. Thanks!
